site_name: Clonechat docs
theme:
  name: 'material'
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: teal 
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode


  features:
    - toc.integrate 

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg